version: '3.7'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: yakHaiJaaiRoot
      MYSQL_DATABASE: yakhaijaai
      MYSQL_USER: yakHaiJaai
      MYSQL_PASSWORD: yakHaiJaai
    ports:
      - '3306:3306'

volumes:
  mysql_data:
